# This is a basic workflow to help you get started with Actions

name: HTML redirect generator

# Controls when the workflow will run
  # Triggers the workflow when issue is opened
on:
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Generate file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "$github.event.issue.title/index.html"
          FILE_DATA: "<script>window.location.href = '$github.event.issue.body';</script>"
          
      - name: Commit
        uses: EndBug/add-and-commit@v9 
        id: commit
        with:
          message: 'generate redirect HTML'
          add: "index.html --force"
          pathspec_error_handling: ignore
          push: true
        
